# Generated by Django 6.0.5 on 2026-05-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acolhido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documentacao', models.CharField(blank=True, default='', max_length=50)),
                ('justificativa_sem_doc', models.TextField(blank=True, default='')),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('familiares', models.TextField(blank=True, default='')),
                ('nome_pais', models.CharField(blank=True, default='', max_length=150)),
                ('endereco', models.CharField(blank=True, default='', max_length=200)),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('historico_saude', models.TextField(blank=True, default='')),
                ('orientacao_sexual', models.CharField(blank=True, default='', max_length=30)),
                ('motivo_acolhimento', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('capacidade_total', models.IntegerField()),
                ('categorizacao', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato', models.CharField(blank=True, default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
