# Generated by Django 6.0.4 on 2026-06-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_Acolhido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_rua', models.BooleanField(default=False)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH'), ('SEM_DOC', 'Sem Documentação')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'SEM_DOC'), _negated=True), fields=('tipo', 'numero'), name='documento_unico_por_tipo')],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade_total', models.IntegerField()),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categorizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituicoes', to='vagas.categoria')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.endereco_instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Contato_Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('valor', models.CharField(max_length=25)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='vagas.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Acolhido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nome_mae', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True)),
                ('familiares', models.TextField(blank=True, default='')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('genero', models.CharField(max_length=20)),
                ('orientacao_sexual', models.CharField(blank=True, default='', max_length=30)),
                ('laudo_medico', models.FileField(blank=True, null=True, upload_to='laudos_saude/')),
                ('motivo_acolhimento', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('documentacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.documentacao')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.endereco_acolhido')),
                ('instituicao_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acolhidos', to='vagas.instituicao')),
            ],
        ),
    ]
