# Generated by Django 6.0.4 on 2026-06-18 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_alter_categoria_nome_alter_instituicao_categorizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAcolhimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('motivo_saida', models.CharField(blank=True, max_length=200, null=True)),
                ('acolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estadias', to='vagas.acolhido')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_vagas', to='vagas.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('acolhido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_atual', to='vagas.acolhido')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='vagas.instituicao')),
            ],
            options={
                'ordering': ['data_solicitacao'],
            },
        ),
    ]
