# Generated by Django 6.0.6 on 2026-06-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
