# Generated by Django 6.0.4 on 2026-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_historicoacolhimento_reservavaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.IntegerField(max_length=14, unique=True),
        ),
    ]
